CiscoDevNet/ansible-meraki

- tests/integration/targets/meraki_device/tasks/main.yml
The integration test referred to camel case variables, which caused an error. This moves it to snake case.
> Change integration test variable from camel case to snake case

- CHANGELOG.md
- plugins/modules/meraki_config_template.py
- tests/integration/targets/meraki_config_template/tasks/main.yml
`nets` was created too late so the module was calling it before it was set to something valid. This PR fixes this crash.
Fixes #19
> Fix crash when unbinding template with net_id in check mode

- plugins/module_utils/network/meraki/meraki.py
- tests/integration/targets/meraki_admin/tasks/main.yml
- tests/integration/targets/meraki_syslog/tasks/main.yml
400 series errors may not pass the right information to the output so it would crash. This reworks the exception handling to improve output and reduce crashes.
> Fix 400 error handling to remove crashes

- CHANGELOG.md
- plugins/module_utils/network/meraki/meraki.py
`is_update_required()` didn't handle exceptions if the types were different. This used to be handled by the type comparison, but since that is removed, this is needed.
This pull request fixes the corner case where the proposed object isn't a dict so `.items()` would crash. The `AttributeError` exception is now handled.
Fixes #6
> Add exception handling to avoid crash when comparing types

- CHANGELOG.md
- tests/integration/targets/meraki_content_filtering/tasks/main.yml
Integration tests for `meraki_content_filtering` now deletes the network upon completion, success or failure.
Fixes #5 and depends on https://github.com/CiscoDevNet/ansible-meraki/pull/7
> Content filtering integration test deletes network after completion

- CHANGELOG.md
- plugins/modules/meraki_firewalled_services.py
- tests/integration/targets/meraki_firewalled_services/tasks/tests.yml
The module didn't look at net_id. This commit fixes that and adds an
integration test.
Fixes #22
> meraki_firewalled_services recognizes net_id

- CHANGELOG.md
- plugins/modules/meraki_admin.py
- plugins/modules/meraki_config_template.py
- plugins/modules/meraki_content_filtering.py
- plugins/modules/meraki_device.py
- plugins/modules/meraki_firewalled_services.py
- plugins/modules/meraki_malware.py
- plugins/modules/meraki_mr_l3_firewall.py
- plugins/modules/meraki_mx_l3_firewall.py
- plugins/modules/meraki_mx_l7_firewall.py
- plugins/modules/meraki_nat.py
- plugins/modules/meraki_network.py
- plugins/modules/meraki_organization.py
- plugins/modules/meraki_snmp.py
- plugins/modules/meraki_ssid.py
- plugins/modules/meraki_static_route.py
- plugins/modules/meraki_switchport.py
- plugins/modules/meraki_syslog.py
- plugins/modules/meraki_vlan.py
- plugins/modules/meraki_webhook.py
Remove all unused import statements and variables based on linting information from Ansible Galaxy. Probably more to come though.
Fixes #13
> Remove unused import statements and variables

- plugins/modules/meraki_mx_l3_firewall.py
The firewall rules didn't have the ability to be reset to a fresh start. It appears a blank list wasn't picked up by an if condition. This PR fixes the problem.
Fixes #12
> Change if condition so resetting firewall rules works

- plugins/module_utils/network/meraki/meraki.py
- plugins/modules/meraki_admin.py
- tests/integration/targets/meraki_admin/tasks/main.yml
- tests/integration/targets/meraki_content_filtering/tasks/main.yml
`ansible-test sanity` was throwing some errors. This PR gets rid of the errors. It also modifies meraki_admin spec to no longer use JSON.
Fixes #29
> Clean up sanity errors

- CHANGELOG.md
- plugins/module_utils/network/meraki/meraki.py
- plugins/modules/meraki_admin.py
- plugins/modules/meraki_content_filtering.py
- plugins/modules/meraki_firewalled_services.py
- plugins/modules/meraki_malware.py
- plugins/modules/meraki_mx_l7_firewall.py
- plugins/modules/meraki_snmp.py
- plugins/modules/meraki_syslog.py
- plugins/modules/meraki_vlan.py
- plugins/modules/meraki_webhook.py
Much of the diff code is repeated through each module. This pull request creates a `generate_diff(before, after)` method which will compare the data structures and assign the results to the module, so no assignment is necessary.
meraki_nat cannot take this method since it uses a more complex data structure to return data.
Fixes to #36
> Create new diff method

- CHANGELOG.md
- plugins/modules/meraki_organization.py
- tests/integration/targets/meraki_organization/tasks/tests.yml
Deleting an organization is catastrophic. This pull request adds a required confirmation for deletion of an organization. This isn't needed and has some pushback within Ansible, but I'm adding it to be safe.
> meraki_organization - Add confirmation for organization deletion

- plugins/modules/meraki_mx_l3_firewall.py
- tests/integration/targets/meraki_mx_l3_firewall/tasks/main.yml
Firewall rules were not updating due to `range()` not working if there was only one non-default firewall rule. This pull request fixes this. I also discovered a bug with integration tests where `any` wasn't matching with the response from Meraki. I consulted Meraki and they clarified what I should expect. I've updated integration tests and documentation to reflect.
Fixes #61 
CC @pokepoke81
> meraki_mx_l3_firewall - Fix firewall rules not updating

- plugins/modules/meraki_organization.py
`delete_confirm` in `meraki_organization` existed but wasn't documented. This PR adds proper documentation.
> Add documentation for delete_confirm

- galaxy.yml
These entries are in your `.gitignore`, so that strongly suggests that it's safe to not put in the build. From a test build, the contents match expectations:
```
$ tree ~/.ansible/collections/ansible_collections/cisco/meraki/
/Users/alancoding/.ansible/collections/ansible_collections/cisco/meraki/
├── CHANGELOG.md
├── FILES.json
├── MANIFEST.json
├── README.md
├── plugins
│   ├── module_utils
│   │   └── network
│   │       └── meraki
│   │           ├── __init__.py
│   │           └── meraki.py
│   └── modules
│       ├── __init__.py
│       ├── meraki_admin.py
│       ├── meraki_config_template.py
│       ├── meraki_content_filtering.py
│       ├── meraki_device.py
│       ├── meraki_firewalled_services.py
│       ├── meraki_intrusion_prevention.py
│       ├── meraki_malware.py
│   …
```
> Add build_ignore to Galaxy metadata

- CHANGELOG.md
- plugins/modules/meraki_mx_l3_firewall.py
- tests/integration/targets/meraki_mx_l3_firewall/tasks/main.yml
This removes an unnecessary org lookup that is triggered when `org_id` and `net_name` are used in tandem. It was causing a crash and wasn't needed anyways.
Fixes #73
> meraki_mx_l3_firewall - Remove unnecessary org lookup

- CHANGELOG.md
- plugins/modules/meraki_mx_l3_firewall.py
- tests/integration/targets/meraki_mx_l3_firewall/tasks/main.yml
This PR fixes idempotency problems due to capitalization of parameters called 'any'. If this works I'll update related modules with the same fix.
Fixes #80
> meraki_mx_l3_firewall - Fix idempotency with any

- CHANGELOG.md
- plugins/modules/meraki_device.py
- tests/integration/targets/meraki_device/tasks/main.yml
Devices would update in unpredictable ways whether or not `hostname` was specified in the parameters. This pull request rewrites much of the module to be more reliable and easier to understand (for me).
This is a pretty large change so much testing is required.
Fixes #98
> meraki_device - Improve reliability of device updates

- CHANGELOG.md
- plugins/modules/meraki_admin.py
- tests/integration/targets/meraki_admin/tasks/main.yml
Fixes #97 
- Module was accepting networks.network key when it shouldn't have
- Module now supports both networks.network and network.id
> meraki_admin - Properly handle network.network and network.id

- changelogs/fragments/sanity_fixes.yml
- plugins/module_utils/network/meraki/meraki.py
v1 of the API has significant changes which will break compatibility. I'm using this opportunity to rewrite the `request()` method to be more reliable and easy to understand.
Fixes #117
> Rewrite request() to be more friendly

- changelogs/fragments/meraki_network_update.yml
- changelogs/fragments/requests-rewrite.yml
- plugins/modules/meraki_network.py
- tests/integration/targets/meraki_network/tasks/main.yml
The v1 API has breaking changes to the API. This PR fixes the `meraki_network` module to work properly under the new API.
> Update meraki_network to be compatible with new API

- changelogs/fragments/meraki_content_filtering.yml
- plugins/modules/meraki_content_filtering.py
API v1 is requiring a different endpoint URL
> meraki_content_filtering - Update URLs for content filtering endpoints in API v1

- changelogs/fragments/ssid_tags.yml
- plugins/modules/meraki_ssid.py
The following error was generated during integration test executions:
```
TASK [meraki_ssid : Set VLAN arg spec] *****************************************
fatal: [localhost]: FAILED! => {"body": {"errors": ["'tags' must be a string"]}, "changed": false, "msg": "HTTP error 400 - https://api.meraki.com/api/v0/networks/numberhere/ssids/1 - [\"'tags' must be a string\"]", "response": "HTTP Error 400: Bad Request", "status": 400}
```
This PR fixes the crash by converting a list to a comma separated string.
> meraki_ssid - Fix formatting on VLAN tags

- changelogs/fragments/diff_secret_fix.yml
- plugins/modules/meraki_webhook.py
- tests/integration/targets/meraki_webhook/tasks/tests.yml
The meraki_webhook module has the possibility of displaying passwords which should be hidden. This PR fixes it. A security notice will be published upon merge. meraki_ssid may have this problem as well and I need to investigate that further.
Fixes #131
> WIP: meraki_webhook - Fix bug which would show values for no log items

- changelogs/fragments/management_ms_fix.yml
- plugins/modules/meraki_management_interface.py
- tests/integration/targets/meraki_management_interface/tasks/main.yml
Fixes #207 
Non-MX devices do not return a `wanEnabled` property so when I was checking for updates, it always required an update. Unfortunately, this meant there was likely no changes so it would crash when generating a diff.
> meraki_management_interface - Fix crash on non-MX devices

- galaxy.yml
The current release (2.1.1) has 122 MB of tests/output/ which are totally unnecessary.
> Reduce next release by 122 MB

- changelogs/fragments/0238-vvlan-allow-null.yml
- plugins/modules/meraki_ms_switchport.py
- tests/integration/targets/meraki_switchport/tasks/main.yml
fixes #238 
This allows the `state: absent` to be specified under `voice_vlan` in order to clear (null) out a voice vlan if it already exist.
> Add nested dictionary for voice_vlan arg_spec to allow a state of absent to remove voice vlan.

- .github/workflows/ansible-test.yml
Ansible is now using Python 3.8 as a minimum version. This PR upgrades to match the requirement.
> Update CICD job to use Python 3.8 instead of 3.6

- changelogs/fragments/lowercase-firewall-protocol.yml
- changelogs/fragments/lowercase-firewall-rule-values.yml
- plugins/modules/meraki_mr_l3_firewall.py
- plugins/modules/meraki_mx_l3_firewall.py
- tests/integration/targets/meraki_mr_l3_firewall/tasks/main.yml
- tests/integration/targets/meraki_mx_l3_firewall/tasks/main.yml
The MR and MX default firewall rule is returned with the value of protocol capitalized as `Any` while the user-defined firewall rules are returned with the value of protocol in all lowercase such as `any`.
The default MR L3 firewall rules are:
`{"comment": "Wireless clients accessing LAN", "policy": "allow", "protocol": "Any", "dest_port": "Any", "dest_cdr": "Local LAN"}`
`{"comment": "Default rule", "policy": "allow", "protocol": "Any", "dest_port": "Any", "dest_cdr": "Any"}`
The default MX L3 firewall rule is:
`{"comment": "Default rule", "policy": "allow", "protocol": "Any", "dest_port": "Any", "dest_cdr": "Any"}`
When attempting to merge existing and new firewall rules, https://docs.ansible.com/ansible/latest/scenario_guides/guide_meraki.html#merging-existing-and-new-data, the MR and …
> Normalize MR and MX default firewall rule protocol value

- changelogs/fragments/meraki_mr_radio.yml
- plugins/modules/meraki_mr_radio.py
- tests/integration/targets/meraki_mr_radio/tasks/main.yml
This module allows users to modify radio settings on an MR device using the `/devices/{serial}/wireless/radio/settings` API.  This is primarily useful under the following situations:
* You've used the `meraki_mr_rf_profile` module to create a profile and need to apply it to one or more APs (currently unsupported by `ansible-meraki` AFAIK)
* You have a static channel plan that you need to manage
Hopefully this covers the bases; I didn't see a contributing guide or how to run/verify the integration tests, so I took a stab at it (which might be wrong, happy to fix those).
> Add module for managing radio settings on MR devices

- changelogs/fragments/delete-ssid-idempotency.yml
- plugins/modules/meraki_mr_ssid.py
- tests/integration/targets/meraki_ssid/tasks/main.yml
When deleting an SSID by name, the `meraki_mr_ssid` module does not current return the expected results.  `get_available_number()` will always return a truthy value as long as there is a free SSID number available.  This ultimately results in `meraki.result.changed` always being `True`, even when no SSID would be deleted.  The bevahior can be reproduced with the following task:
```yaml
- name: Remove Default SSID
cisco.meraki.meraki_mr_ssid:
org_id: "{{ meraki_org_id }}"
net_name: "{{ meraki_net_name }}"
name: "{{ meraki_net_name }} WiFi"
state: absent
```
Running the task above more than once will result in Ansible reporting a change, even though the SSID no longer exists.
To fix the issue, this MR leaves the existing logic intact but adds an early exit and sets `meraki.result.changed` …
> Fix issue with SSID removal idempotency when ID doesn't exist

- changelogs/fragments/mx_l7_firewall_empty_list.yaml
- plugins/module_utils/network/meraki/meraki.py
- plugins/modules/meraki_mx_l7_firewall.py
- tests/integration/targets/meraki_mx_l7_firewall/tasks/tests.yml
This PR will delete rules when an empty ruleset is provided for `rules` and `state: present`. As of now, there is no `state: absent` function but that may come in a future version as I can see how that can be useful for removing individual rules.
This also improves error handling for when Ansible returns no response. Currently it fails but will eventually retry.
Fixes #257
> meraki_mx_l7_firewall - Delete rules with empty ruleset

- changelogs/fragments/288-syslog_idempotency.yml
- changelogs/fragments/rf-profile-create-idempotency.yml
- plugins/modules/meraki_mr_rf_profile.py
- plugins/modules/meraki_syslog.py
- tests/integration/targets/meraki_mr_rf_profile/tasks/main.yml
- tests/integration/targets/meraki_syslog/tasks/main.yml
Fixes #288 
meraki_syslog would crash when multiple roles were provided and not in the same order. This PR adds a sort function to sort the roles so it would work properly. This also runs `black` on code.
> meraki_syslog - Fix crash with out of order roles

- tests/integration/targets/meraki_mr_rf_profile/tasks/main.yml
!289 merged the commits from !281 but without/before the tests were fixed per the feedback in that PR.  This PR fixes those tests.
> Fix RF Profile tests from !281

- CHANGELOG.rst
- changelogs/fragments/meraki_mr_ssid.yaml
- plugins/modules/meraki_mr_ssid.py
- tests/integration/targets/meraki_mr_ssid/meraki_ssid/tasks/main.yml
Add `visible` to `meraki_mr_ssid`
```
Boolean indicating whether APs should advertise or hide this SSID. APs will only broadcast this SSID if set to true
> Add `visible` argument to meraki_mr_ssid

- changelogs/fragments/fix-meraki-mr-radio-tests.yml
- tests/integration/targets/meraki_mr_radio/tasks/main.yml
Resolving: #380 
I got the error:
```
Running meraki_mr_radio integration test role                                                                                                                 [WARNING]: running playbook inside collection cisco.meraki
PLAY [meraki] ******************************************************************
TASK [meraki_mr_radio : Create network with type wireless] *********************
[WARNING]: Platform darwin on host localhost is using the discovered Python
interpreter at /opt/homebrew/bin/python3.11, but future installation of another
Python interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.14/reference_appendices/interpreter_discovery.html for more information.
fatal: [localhost]: FAILED! => {"changed": false, …
```
> Fix test meraki mr radio

- changelogs/fragments/meraki_webhook_payload_template.yml
- plugins/modules/meraki_webhook_payload_template.py
- tests/integration/targets/meraki_webhook_payload_template/aliases
- tests/integration/targets/meraki_webhook_payload_template/tasks/main.yml
- tests/integration/targets/meraki_webhook_payload_template/tasks/tests.yml
This module allows users to [manage webhook payload templates](https://developer.cisco.com/meraki/api-latest/#!delete-network-webhooks-payload-template) using the /networks/{networkId}/webhooks/payloadTemplates/ API.
I am unable to run integration tests, so I can't verify that I got every base covered.
```- name: Create payload template
meraki_webhook_payload_template:
auth_key: abc12345
org_name: YourOrg
state: query
name: TestTemplate
body: Testbody
headers:
- name: testheader
template: testheadertemplate
delegate_to: localhost
```
> Add module for managing webhook payload templates

- changelogs/fragments/bugfixes-meraki_webhook_payload_template.yml
- plugins/modules/meraki_webhook_payload_template.py
- generate diffs in `meraki_webhook_payload_template` when updating a template
- When running in `check_mode`, fix function to NOT actually update the template
> Fix meraki_webhook_payload_template update to support checkmode

- .github/workflows/ansible-lint.yml
- changelogs/fragments/workflow-ansible-lint.yml
Based on comment created by @kbreit: https://github.com/CiscoDevNet/ansible-meraki/issues/361#issuecomment-1380351426.
Tested on my repo. I tested:
- When the files are tests and do not need fix: https://github.com/y0rune/ansible-meraki/actions/runs/3920508043/jobs/6702184903
- When the files are tests and need fix: https://github.com/y0rune/ansible-meraki/actions/runs/3920457842
- When the files are not the testes: https://github.com/y0rune/ansible-meraki/actions/runs/3920471067/jobs/6702123996 - the test will skip the installation process
Should I test more cases?
Thank you!
Marcin
BTW: In the next week I will work of the comments you told me @kbreit in the several commits ;)
> Added the simple workflow for ansible-lint

- changelogs/fragments/issue-meraki_mx_content_filtering.yml
- plugins/modules/meraki_mx_content_filtering.py
Resolved issue with empty params (when it was resetting)
> Trying resolving issue with meraki_mx_content_filtering

- changelogs/fragments/433_Resolve_meraki_webhook_fail_when_none_defined.yml
- changelogs/fragments/Resolve_meraki_webhook_fail_when_none_defined.yml
- plugins/modules/meraki_webhook.py
- tests/integration/targets/meraki_webhook/tasks/tests.yml
Resolves issue #433
Original Issue report concerned meraki_webhook failing when a query returns a list with no entries.
PR adds test coverage for the observed issue, and makes ```sanitize_no_log_values``` work with lists of any length. 
sanity and integration tests passed.
> Resolve meraki webhook fail when none defined

- changelogs/fragments/Resolve_shared_secret_defaulting_to_null.yml
- plugins/modules/meraki_webhook.py
- tests/integration/targets/meraki_webhook/tasks/tests.yml
Resolves #439 meraki_webhook defaults shared_secret to null which clashes with API behaviour.
- tests for the presence of shared_secret before setting it in the API call;
- Additionally test coverage has been added and a number of linting issues with the testcase file resolved.
> Resolve meraki webhook sharedsecret idempotency

- changelogs/fragments/Resolve_meraki_network_query_by_ID_returns_empty_data_object.yml
- plugins/modules/meraki_network.py
- tests/integration/targets/meraki_network/tasks/main.yml
Resolves #441 meraki_network query by ID returns empty data object
- adds test coverage for meraki_network query by net_id
- adds net_id to the meraki_network query call
> Resolve meraki network query by id returns empty data object
