CiscoDevNet/ansible-meraki

galaxy.yml

`galaxy.yml` will link to the issues page. This PR adds that URL.

Add issues URL to galaxy.yml

---

CHANGELOG.md
plugins/modules/meraki_config_template.py
plugins/modules/meraki_malware.py
plugins/modules/meraki_mr_l3_firewall.py
plugins/modules/meraki_mx_l3_firewall.py
plugins/modules/meraki_mx_l7_firewall.py
plugins/modules/meraki_nat.py
plugins/modules/meraki_network.py
plugins/modules/meraki_organization.py
plugins/modules/meraki_snmp.py
plugins/modules/meraki_ssid.py
plugins/modules/meraki_switchport.py
plugins/modules/meraki_syslog.py
plugins/modules/meraki_vlan.py

Documentation had a significant number of errors, specifically around types. This PR fixes those changes.

Fix documentation for ansible-test compliance

---

tests/integration/targets/meraki_webhooks/aliases
tests/integration/targets/meraki_webhooks/tasks/main.yml
tests/integration/targets/meraki_webhooks/tasks/tests.yml

When importing from Ansible the webhooks tests werent included. This
readds them.
Fixes #15

Re-add tests for meraki_webhooks

---

CHANGELOG.md

Changelog is now broken into different sections for features, bugfixes,
and documentation.

Reformat Changelog

---

CHANGELOG.md
plugins/modules/meraki_ssid.py
tests/integration/targets/meraki_ssid/tasks/main.yml

This is based on issue https://github.com/ansible/ansible/issues/65738 at the ansible/ansible repository.

meraki_ssid - Properly format walled garden payload to Meraki

---

CHANGELOG.md
plugins/modules/meraki_device.py
plugins/modules/meraki_mr_l3_firewall.py
plugins/modules/meraki_mx_l3_firewall.py
plugins/modules/meraki_ssid.py
plugins/modules/meraki_switchport.py

- Some modules had supports_check_mode as True when it wasn't right
- Changes to False

Disable checkmode for modules which don't support it

---

plugins/modules/meraki_switch_access_list.py
tests/integration/targets/meraki_switch_access_list/aliases
tests/integration/targets/meraki_switch_access_list/tasks/main.yml
tests/integration/targets/meraki_switch_access_list/tasks/tests.yml

New module adds support for configuring access lists for MX switches.

New module -  meraki_switch_access_list

---

CHANGELOG.md
plugins/modules/meraki_admin.py
plugins/modules/meraki_config_template.py
plugins/modules/meraki_content_filtering.py
plugins/modules/meraki_firewalled_services.py
plugins/modules/meraki_malware.py
plugins/modules/meraki_mx_l7_firewall.py
plugins/modules/meraki_ssid.py
plugins/modules/meraki_syslog.py
plugins/modules/meraki_vlan.py
plugins/modules/meraki_webhook.py

There were a few sanity errors in 0.1.0. This fixes them.

Sanity fixes for v0.1.0

---

galaxy.yml

There were a few sanity errors in 0.1.0. This fixes them.

Increment version to v0.1.1.

---

plugins/modules/meraki_config_template.py
plugins/modules/meraki_snmp.py

This PR will fix a few sanity check PR errors. There are more coming but this should help the open ones.

Fix Galaxy sanity check errors

---

CHANGELOG.md
plugins/modules/meraki_intrusion_prevention.py
tests/integration/targets/meraki_intrusion_prevention/aliases
tests/integration/targets/meraki_intrusion_prevention/tasks/main.yml
tests/integration/targets/meraki_intrusion_prevention/tasks/tests.yml

This was initially created for the mainline Ansible code but was never merged.

New module - meraki_intrusion_prevention

---

CHANGELOG.md
plugins/modules/meraki_mx_l3_firewall.py
tests/integration/targets/meraki_mx_l3_firewall/tasks/main.yml

- Add check mode support
- Also fix a bug for change checking when rules isn't called

meraki_mx_l3_firewall - Add check mode

---

CHANGELOG.md
plugins/modules/meraki_mr_l3_firewall.py
tests/integration/targets/meraki_mr_l3_firewall/tasks/main.yml

The code is ugly but seems to work.

meraki_mr_l3_firewall - Add check mode

---

plugins/modules/meraki_mx_l3_firewall.py

Fix indentation in meraki_mx_l3_firewall

---

CHANGELOG.md
plugins/modules/meraki_static_route.py
tests/integration/targets/meraki_static_route/tasks/main.yml

Fixes #70 
@pokepoke81 - Please test this PR to see if this fixes the bug.

meraki_static_route - Fix idempotency bugs with certain parameters

---

plugins/modules/meraki_intrusion_prevention.py
plugins/modules/meraki_snmp.py

Remove a few imports which are causing warnings in linting.

Remove imports to make linting happy

---

plugins/modules/meraki_mx_site_to_site_firewall.py
tests/integration/targets/meraki_mx_site_to_site_firewall/aliases
tests/integration/targets/meraki_mx_site_to_site_firewall/tasks/main.yml

This module is almost identical to `meraki_mx_l3_firewall`.
@pokepoke81 Please test this PR.

New module - meraki_mx_site_to_site_firewall

---

CHANGELOG.md
plugins/modules/meraki_vlan.py
tests/integration/targets/meraki_vlan/tasks/main.yml

- Documentation and tests
Fixes #63

Add support for DHCP configuration

---

CHANGELOG.md
plugins/modules/meraki_site_to_site_vpn.py
tests/integration/targets/meraki_site_to_site_vpn/aliases
tests/integration/targets/meraki_site_to_site_vpn/tasks/main.yml

New Module - meraki_site_to_site_vpn

---

CHANGELOG.md
plugins/modules/meraki_site_to_site_vpn.py
tests/integration/targets/meraki_site_to_site_vpn/tasks/main.yml

- Changed status was never applied
- Idempotency checks weren't enabled on the first release
- Tests added to integration tests

Enable idempotency on site to site VPN module

---

doc_fragments/meraki.py

Adds a documentation fragment which was missing. Fixes #96

Add documentation fragment

---

plugins/doc_fragments/meraki.py
plugins/module_utils/network/meraki/meraki.py
plugins/modules/meraki_mx_l7_firewall.py

Adding CICD checks opened up a bunch of errors so this PR will attempt to fix as many as possible.

Fix miscellaneous CICD errors

---

changelogs/fragments/meraki_webhook.yml
plugins/modules/meraki_webhook.py
tests/integration/targets/meraki_webhook/tasks/tests.yml

Depends on #120 for error handling

meraki_webhook - Update for v1 API

---

changelogs/fragments/meraki_syslog.yml
plugins/modules/meraki_syslog.py
tests/integration/targets/meraki_syslog/tasks/main.yml

WIP: meraki_syslog - Update documentation and tests for v1

---

changelogs/fragments/meraki_snmp.yml
plugins/modules/meraki_snmp.py
tests/integration/targets/meraki_snmp/tasks/main.yml

Update endpoints to new ones in v1. Also fix a camel case response in the documentation.
Depends on #120

WIP: meraki_snmp - Update URLs for v1

---

changelogs/fragments/meraki_webhook.yml
plugins/modules/meraki_webhook.py
tests/integration/targets/meraki_webhook/tasks/tests.yml

meraki_webhook - Fix responses and crash in webhook

---

changelogs/fragments/meraki_device.yml
plugins/modules/meraki_device.py
tests/integration/targets/meraki_device/tasks/main.yml

- Remove lldp and uplink query parameters
- Added new query parameter

meraki_device - Update module for API v1

---

changelogs/fragments/build_ignore.yml
galaxy.yml

This PR will add items which shouldn't be in the built and distributed collections bundle.

Add build_ignore items and changelog fragment for 1.0

---

CHANGELOG.md
changelogs/fragments/meraki_wpa3_transition.yml
plugins/modules/meraki_ssid.py
tests/integration/targets/meraki_ssid/tasks/main.yml

I believe this covers what would be needed. I double checked the Meraki Dashboard SDK and it looks like it is those two options being added. Let me know if otherwise should be looked at.
Fixes #81

Adds WPA3 spec to options

---

plugins/module_utils/network/meraki/meraki.py

The rewrite of the `request()` method in 2.0 required me to test the 429 retry functionality. It wasn't working so this one fixes it. Turns out, if there's more than 10 requests from an IP it doesn't return a retry-after field.

Fix 429 retry functionality

---

changelogs/fragments/meraki_ms_ospf.yml
plugins/modules/meraki_ms_ospf.py
tests/integration/inventory.networking.template
tests/integration/targets/meraki_ms_ospf/tasks/main.yml

Configure OSPF on MS networks
Closes #164

New module - meraki_ms_ospf

---

changelogs/fragments/meraki_ms_l3_interface.yml
plugins/modules/meraki_ms_l3_interface.py
tests/integration/targets/meraki_ms_l3_interface/tasks/main.yml

New module - meraki_ms_l3_interface

---

changelogs/fragments/is_update_debug.yml
plugins/module_utils/network/meraki/meraki.py

- This is useful for developer debugging
- No end user changes

meraki - Add optional debugging for is_update_required() method

---

changelogs/fragments/malware_mx_l2_interface.yml
plugins/modules/meraki_mx_l2_interface.py
tests/integration/targets/meraki_mx_l2_interface/tasks/main.yml

New module - meraki_mx_l2_interface

---

changelogs/fragments/meraki_alert.yml
plugins/module_utils/network/meraki/meraki.py
plugins/modules/meraki_alert.py
tests/integration/targets/meraki_alert/tasks/main.yml

New module - meraki_alert

---

changelogs/fragments/pagination.yml
plugins/module_utils/network/meraki/meraki.py
plugins/modules/meraki_device.py
plugins/modules/meraki_network.py

- Enable pagination for devices and networks
- This allows for more than 1,000 items to be returned
Fixes #214

Add support for pagination

---

changelogs/fragments/network_settings_changed.yml
plugins/module_utils/network/meraki/meraki.py
plugins/modules/meraki_network.py
tests/integration/targets/meraki_network/tasks/main.yml

@petertavenier - Can you please test this pull request?
Fixes #201

meraki_network - Fix local and remote status changed state bug

---

changelogs/fragments/ssid_ise.yml
plugins/modules/meraki_mr_ssid.py

meraki_ssid - Add ISE as splash page option

---

changelogs/fragments/switchport-docs.yaml
plugins/modules/meraki_ms_switchport.py
tests/sanity/ignore-2.10.txt

Improve documentation about responses

Improve meraki_mx_switchport response documentation

---

changelogs/fragments/sanity-fixes.yml

Add missing changelog entry

---

changelogs/.plugin-cache.yaml
changelogs/CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/sanity-fixes.yml
galaxy.yml

Release v 2.4.2

---

plugins/modules/meraki_ms_stack.py
plugins/modules/meraki_ms_stack_l3_interface.py
tests/integration/targets/meraki_ms_stack_l3_interface/tasks/main.yml

Add meraki_ms_stack_l3_interface module

---

changelogs/fragments/docs-contributing.yml
contributing.md

Fixes #282 
@holynakamoto Please review and let me know if you have any thoughts. I'll merge in the next few days if I don't hear back and we can do patches from there.

Ad contributing.md file

---

changelogs/fragments/290-sponsor.yml
plugins/modules/meraki_mr_ssid.py
tests/integration/targets/meraki_ssid/tasks/main.yml

meraki_ssid - Add support for new args

---

changelogs/310-alert-webhook
plugins/modules/meraki_alert.py
tests/integration/targets/meraki_alert/tasks/main.yml

meraki_alert - Properly set HTTP webhook ID

---

CHANGELOG.rst
changelogs/.plugin-cache.yaml
changelogs/changelog.yaml
changelogs/fragments/288-fix-dict.yml
changelogs/fragments/310-alert-webhook.yml
changelogs/fragments/ee.yml
changelogs/fragments/net_type-list.yml
galaxy.yml

- Increment version
- Move CHANGELOG.rst into root directory

Prepare release of v2.6.2

---

changelogs/fragments/s2s_peers.yaml
plugins/modules/meraki_mx_third_party_vpn_peers.py
tests/integration/targets/meraki_mx_third_party_vpn_peers/aliases
tests/integration/targets/meraki_mx_third_party_vpn_peers/tasks/main.yml

Add meraki_mx_third_party_vpn_peers module

---

changelogs/fragments/meraki_mx_network_vlan_settings.yml
plugins/modules/meraki_mx_network_vlan_settings.py
tests/integration/targets/meraki_mx_network_vlan_settings/tasks/main.yml

Add meraki_mx_network_vlan_settings module

---

changelogs/fragments/327-switchport-flex.yaml
changelogs/fragments/action_batch.yaml
plugins/modules/meraki_ms_switchport.py
tests/integration/targets/meraki_switchport/tasks/main.yml

meraki_switchport - Add support for flexible stacking port configuration

---

changelogs/fragments/331-switchport_clear_vlan.yml
plugins/modules/meraki_ms_switchport.py
tests/integration/targets/meraki_switchport/tasks/main.yml

meraki_switchport - Setting VLAN 0 on trunk port clears the VLAN

---

changelogs/fragments/335-net_copy.yml
plugins/modules/meraki_network.py
tests/integration/targets/meraki_network/tasks/main.yml

meraki_network - Add support for copy_from_network_id

---

changelogs/fragments/changelog-frags.yml
changelogs/fragments/sublime-utils.yml
scripts/sublime-build/build.py.generic
tests/sanity/ignore-2.14.txt

Change shebang to point to env

---

plugins/modules/meraki_syslog.py

- The documentation mentioned 'state' as 'status' in 3 places.
- To set the values the state should be 'present' and not 'query' in 2 of the examples

rectified the documentation

---

changelogs/fragments/add-meraki_ms_access_policy.yml
plugins/modules/meraki_ms_access_policies.py
tests/integration/targets/meraki_ms_access_policies/tasks/main.yml

Hello!
I saw in the ansible-meraki we do not have a module for access polices for switches. So I decided to create that one ;)
Please review my PR.
Thank you!

Added meraki_ms_access_polices into a ansible-meraki

---

changelogs/fragments/meraki_ms_switch_pollicy_doc.yml
plugins/modules/meraki_ms_access_policies.py

Mistyped documentation in module meraki_ms_access_policies rectified

doc rectified for meraki_ms_access_policies

---

changelogs/fragments/webhook-diff.yml
plugins/modules/meraki_webhook.py
tests/integration/targets/meraki_webhook/tasks/tests.yml

Fix #388 for webhook diffs

---

changelogs/fragments/webhook-plus-payload-templates.yml
plugins/modules/meraki_webhook.py
tests/integration/targets/meraki_webhook/tasks/tests.yml

- extend webhook module to support payload templates
- add tests to test the additional functionality
- Reformatted the webhook module using [black](https://black.readthedocs.io/en/stable/)

Add payload template parameter to webhook module

---

changelogs/fragments/mx-s2s.yaml
plugins/modules/meraki_mx_site_to_site_vpn.py
tests/integration/targets/meraki_mx_site_to_site_vpn/tasks/main.yml

@DerrickTJ Please test this if you can. This should solve the bug.
Fixes #410

Perform checks for check mode instead of submitting

---

changelogs/fragments/412-meraki_network-settings.yaml
plugins/modules/meraki_network_settings.py
tests/integration/targets/meraki_network_settings/aliases
tests/integration/targets/meraki_network_settings/tasks/main.yml

Add meraki_network_settings module

---

changelogs/fragments/414-alert-emails.yaml
plugins/modules/meraki_alert.py
tests/integration/targets/meraki_alert/tasks/main.yml

meraki_alert - Fix some alert notifications so they don't crash

---

.github/workflows/changelog.yml
changelogs/fragments/pipeline-changelog.yaml

Update version of tj-action/changed-files

---

changelogs/fragments/issue-451.yml
plugins/modules/meraki_ms_switchport.py
tests/integration/targets/meraki_ms_switchport/tasks/main.yml

ms_switchport: Resolved issue with link_negotation

---

changelogs/fragments/302-firewallorder.yaml
plugins/modules/meraki_mx_site_to_site_firewall.py
tests/integration/targets/meraki_mx_site_to_site_firewall/tasks/main.yml

Fix ordering bugs for firewall rules

---

changelogs/fragments/device-urls.yaml
plugins/modules/meraki_device.py

Fixes #459 
Meraki v1.33 broke this.

meraki_device - Fix endpoint URLs
